const fs = require('fs');
let home = fs.readFileSync('index.html', 'utf8');
const announcement = '<section class="donate-banner" aria-label="Support renewable energy"><span>Build the renewables-based economy with us.</span><a href="https://buy.stripe.com/fZu3cof8867Bbil45VbMQ00" target="_blank" rel="noopener">Donate today! <span>↗</span></a></section>';
const searchOverlay = '<section class="search-overlay" hidden><button class="search-close" type="button" aria-label="Close search">&times;</button><form action="index.html#site-search"><label for="overlay-search">What are you looking for?</label><div><input id="overlay-search" name="q" type="search" placeholder="Search services, regions or topics" autocomplete="off"><button class="button dark">Search</button></div><div class="live-search-results" role="status"></div></form></section>';
home = home.replace(/<section class="donate-banner"[\s\S]*?<\/section>/g, '');
home = home.replace(/<a class="(?:brand )?sidebar-brand"[\s\S]*?<\/a>/, '<strong>Explore Alternate</strong>');
home = home.replace('<strong>Explore Alternate</strong>', '<strong>Explore Alternate</strong>');
const nav = '<nav id="navigation" aria-label="Main navigation"><a href="index.html">Home</a><a href="about.html">About Us</a><a href="solutions.html">Our Services</a><a href="index.html#locations">Where We Work</a><a href="contact.html">Contact Us</a></nav>';
home = home.replace(/<nav id="navigation"[\s\S]*?<\/nav>/, nav)
  .replace(/class="brand" href="#"/g, 'class="brand" href="index.html"')
  .replace('class="button small header-cta" href="#contact"', 'class="button small header-cta" href="contact.html"');
const services = [
  {slug:'solar-installation', name:'Solar installation', title:'Your roof. A brighter future.', intro:'Explore a solar system designed around your property, your electricity needs and your plans for the future.', items:[['Start with your property','Tell us whether your project is a home, business or new development. Roof space, shading and the way you use electricity help shape the conversation.'],['Plan the right system','A site assessment helps establish the suitable layout, system size and installation requirements. Your proposal should explain the scope, costs and next steps.'],['Installation and handover','Agree the installation plan and site access before work begins. At handover, discuss system operation, documentation and ongoing maintenance.']], prep:['Your city and country','Property type and roof photographs, if available','Recent electricity usage or bills','Your preferred project timeline'], faq:[['Can I get a price before a site assessment?','We can discuss your requirements first. A project-specific quotation depends on the property, system scope and any site assessment needed.'],['Will solar cover all my electricity use?','That depends on system size, sunlight and when you use electricity. We can discuss the expected contribution as part of the proposal; full independence is not assumed.']]},
  {slug:'solar-maintenance', name:'Solar maintenance', title:'Keep good energy going.', intro:'Give your solar system the attention it needs. Talk to us about inspections, performance concerns and ongoing care.', items:[['Understand your system','Share the system age, equipment details and any monitoring information you have. This helps us understand your setup before arranging the next step.'],['Investigate concerns','Lower output, equipment alerts or visible damage can be reasons to request an assessment. Describe what changed and when you first noticed it.'],['Plan ongoing care','Discuss a maintenance scope that suits your equipment and site. Any proposed work, parts and visit arrangements should be agreed before proceeding.']], prep:['System location and installation year','Inverter and panel details, if known','Any error messages or changes in output','Details of previous maintenance'], faq:[['Can you look at a system installed by another company?','Send the equipment details and location so we can confirm whether we can support your installation.'],['Should I inspect rooftop equipment myself?','Leave roof access and electrical work to suitably qualified professionals. You can share information from your existing monitoring app without accessing the equipment.']]},
  {slug:'rooftop-partnerships', name:'Commercial rooftop partnerships', title:'More potential above your business.', intro:'An unused commercial rooftop can be the beginning of a solar partnership. Explore what could work for your building and organisation.', items:[['Explore the opportunity','Commercial property owners and authorised occupiers can start a conversation about available roof space and energy needs.'],['Assess the practicalities','Roof condition, structure, access, ownership and electricity arrangements all matter. An assessment helps establish whether a partnership is feasible.'],['Agree a clear arrangement','Discuss responsibilities, access, maintenance, duration and commercial terms. The right arrangement depends on the site and is agreed individually.']], prep:['Property location and building use','Approximate roof area and condition','Ownership or lease arrangements','Your business electricity requirements'], faq:[['Is every commercial roof suitable?','Suitability depends on the roof structure, condition, shading, access and other site requirements. We assess the opportunity before proposing a partnership.'],['What are the commercial terms?','Terms are specific to each project. Contact us to discuss the site; no standard rent, savings or financing arrangement is assumed.']]},
  {slug:'direct-solar-power', name:'Direct solar power supply', title:'Power with a closer connection.', intro:'Explore electricity supplied directly from our solar systems, with an arrangement built around your site and energy requirements.', items:[['Share your demand','Tell us how your property uses electricity throughout the day and what you want a solar supply arrangement to achieve.'],['Explore a site-based supply','We discuss the potential to supply power from a solar system connected to your site, including technical feasibility and the proposed scope.'],['Understand the agreement','Review metering, pricing, maintenance responsibilities and the supply term before proceeding. Arrangements are subject to site assessment and agreement.']], prep:['Site location and property type','Recent electricity consumption','Typical operating hours','Your current electricity arrangements'], faq:[['Is this a grid electricity tariff?','This service concerns power supplied directly from our solar systems. It is not a general grid electricity switching service.'],['What happens when solar generation is low?','Solar output varies with daylight and weather. Your proposal needs to address how remaining electricity demand is met; uninterrupted supply from solar alone is not promised.']]}
];
services.forEach(service => {
  home = home.replace(`href="#contact" data-service="${service.name}"`, `href="${service.slug}.html"`);
});
home = home.replace('href="#about" aria-label="Learn about Alternate Energies"', 'href="about.html" aria-label="Learn about Alternate Energies"');
const statisticsSection = `<section class="statistics-strip" id="statistics"><div class="statistics-heading"><p>Our progress at a glance</p><h2>Building a more<br><span>connected energy future.</span></h2><a class="text-link" href="statistics.html">Browse all statistics &#8599;</a></div><div class="statistics-grid"><div><strong class="count-up" data-target="2850" data-suffix="+">0</strong><span>Customers supported</span></div><div><strong class="count-up" data-target="64">0</strong><span>Team members</span></div><div><strong class="count-up" data-target="42">0</strong><span>Partner profiles</span></div><div><strong class="count-up" data-target="2011">0</strong><span>Established in the UK</span></div></div></section>`;
const missionSection = `<section class="mission-banner"><h2>Supporting <strong>Communities Across East Africa</strong><br>With Practical Solar Energy For A Brighter Future.</h2><a class="mission-link" href="about.html">Read About Us <span>↗</span></a><div class="mission-stat"><strong class="count-up" data-target="1505">0</strong><span>MARKETS</span><small>East Africa, London &amp; Norwich</small></div></section>`;
const videoSection = `<section class="video-section"><div class="video-heading"><p class="eyebrow"><span class="dot"></span>See Solar In Action</p><h2>Energy That Moves<br><span>Communities Forward.</span></h2></div><div class="video-frame"><video src="assets/vid.mp4" title="Renewable energy video" muted playsinline loop preload="metadata"></video><button class="video-mute" type="button" aria-label="Unmute video" aria-pressed="false"><svg class="icon-muted" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 10v4h4l5 4V6l-5 4H4Zm12 1 4 4m0-4-4 4"/></svg><svg class="icon-unmuted" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 10v4h4l5 4V6l-5 4H4Zm12-1a4 4 0 0 1 0 6m2-9a8 8 0 0 1 0 12"/></svg></button></div></section>`;
home = home.replace(/\s*<section class="mission-banner">[\s\S]*?<\/section>/g, '');
home = home.replace(/<section class="statistics-strip"[\s\S]*?<\/section>/g, '');
home = home.replace('<section class="section process">', statisticsSection+'<section class="section process">');
home = home.replace('  <div class="intro-strip company-strip">', '  '+missionSection+'\n  <div class="intro-strip company-strip">');
home = home.replace(/\s*<section class="video-section">[\s\S]*?<\/section>/g, '');
home = home.replace('<section class="contact section"', videoSection+'<section class="contact section"');
home = home.replace('<header', announcement+'<header');
home = home.replace('</header>', '</header>'+searchOverlay);
fs.writeFileSync('index.html', home);
const header = home.match(/<header[\s\S]*?<\/header>/)[0] + (home.match(/<div class="sidebar-backdrop"[\s\S]*?<\/aside>/)?.[0] || '');
let footer = home.match(/<footer[^>]*>[\s\S]*?<\/footer>/)[0];
const footerNav = '<nav class="footer-pages" aria-label="Explore the website"><a href="index.html">Home</a><a href="about.html">Our company</a><a href="solutions.html">All solutions</a>'+services.map(s=>`<a href="${s.slug}.html">${s.name}</a>`).join('')+'<a href="contact.html">Contact</a></nav>';
footer = footer.replace(/<nav class="footer-pages"[\s\S]*?<\/nav>/, '').replace('<footer>', '<footer>'+footerNav);
home = home.replace(/<footer[^>]*>[\s\S]*?<\/footer>/, footer);
fs.writeFileSync('index.html', home);
function page(file, title, description, body) {
 const activeHeader = header.replace(/ aria-current="page"/g, '').replaceAll(`href="${file}"`, `href="${file}" aria-current="page"`);
 fs.writeFileSync(file, `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="${description}"><meta name="theme-color" content="#173c31"><title>${title} | Alternate Energies</title><link rel="stylesheet" href="styles.css"><script src="script.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a>${announcement}${activeHeader}${searchOverlay}<main id="main">${body}</main>${footer}</body></html>`);
}
function hero(title, intro, breadcrumb='') {return `<section class="page-hero"><div class="breadcrumbs"><a href="index.html">Home</a> / ${breadcrumb || title}</div><h1>${title}</h1><p>${intro}</p></section>`;}
function cta(service='') {return `<section class="page-cta"><div><h2>Let’s take the next step.</h2><p>Tell us about your location, your property and your plans.</p></div><a class="button lime" href="contact.html${service?'?service='+encodeURIComponent(service):''}#contact">Discuss your project <span>↗</span></a></section>`;}
services.forEach(s=>page(s.slug+'.html',s.name,s.intro,hero(s.title,s.intro,`<a href="solutions.html">Our solutions</a> / ${s.name}`)+`<section class="section"><div class="section-heading"><h2>A clear path forward.</h2><p>${s.name} across East Africa,<br>London and Norwich.</p></div><div class="steps">${s.items.map(([t,p],i)=>`<article><span>0${i+1}</span><h3>${t}</h3><p>${p}</p></article>`).join('')}</div></section><section class="section detail-grid"><div><h2>Make your first<br>conversation count.</h2><p>You do not need every detail to get started. Share what you have, and we can take it from there.</p></div><div class="checklist"><h3>Helpful information to share</h3><ul>${s.prep.map(p=>`<li>${p}</li>`).join('')}</ul></div></section><section class="section faq"><h2>A few useful answers.</h2>${s.faq.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</section>`+cta(s.name)));
const cards = home.match(/<div class="service-grid">[\s\S]*?\n    <\/div>/)[0];
page('solutions.html','Our solar solutions','Find the right solar service for your property, from installation and maintenance to rooftop partnerships and direct supply.',hero('Solar, around you.','Four connected ways to make solar part of your property’s future. Explore the service that fits your next step.')+`<section class="section">${cards}</section><section class="section detail-grid"><div><h2>Not sure where<br>to start?</h2><p>A new solar project starts with installation. For an existing system, explore maintenance. Commercial roof owners can discuss partnerships, while businesses looking for site-based electricity can explore direct solar supply.</p></div><div class="checklist"><h3>Where we work</h3><p>We welcome enquiries across all East African countries, London and Norwich. Share your exact location so we can discuss site access and project arrangements.</p><a class="text-link" href="contact.html">Ask us about your project ↗</a></div></section>`+cta());
page('about.html','About Us','Learn about Alternate Energies Limited, our company profile, mission, vision and values.',fs.readFileSync('about-content.inc','utf8')+fs.readFileSync('company-details.inc','utf8'));
const contact = home.match(/<section class="contact section"[\s\S]*?<\/section>/)[0];
page('contact.html','Contact us','Contact Alternate Energies for solar projects, general enquiries and purchasing across East Africa, London and Norwich.',hero('Let’s talk solar.','Whether you have a plan, a question or a rooftop with potential, choose the right team below and start a conversation.')+contact+`<section class="section detail-grid"><div><h2>Across borders.<br>Within reach.</h2><p>Serving all East African countries, London and Norwich. Include your city and country in your enquiry to help us understand your project location.</p></div><div class="checklist"><h3>Registered office</h3><p>20 Central Avenue<br>St. Andrews Business Park<br>Norwich, Norfolk<br>England, NR7 0HR</p><p>Please arrange any visit with the team in advance.</p></div></section>`);
console.log('Updated homepage and generated seven connected pages.');

const companyFooter = '<section class="connect-band"><h2>Connect with us</h2><a href="mailto:sales@alternateenergieslimited.com">Sales enquiries &#8599;</a><a href="mailto:info@alternateenergieslimited.com">General enquiries &#8599;</a><a href="mailto:purchase@alternateenergieslimited.com">Purchasing &#8599;</a></section><footer id="footer" class="institution-footer"><div class="footer-columns"><section><h2>Contact Us</h2><p>Alternate Energies Limited<br>20 Central Avenue<br>St. Andrews Business Park<br>Norwich, Norfolk, England, NR7 0HR</p><a href="mailto:info@alternateenergieslimited.com">info@alternateenergieslimited.com</a></section><nav aria-label="Useful links"><h2>Useful Links</h2><a href="index.html">Home</a><a href="about.html">About Us</a><a href="solutions.html">Our Services</a><a href="index.html#locations">Where We Work</a><a href="contact.html">Contact Us</a></nav><nav aria-label="Solar services"><h2>Our Services</h2>'+services.map(s=>'<a href="'+s.slug+'.html">'+s.name+'</a>').join('')+'</nav></div><div class="institution-copyright"><p>&copy; 2011&ndash;<span id="year">2026</span> Alternate Energies Limited. All rights reserved.</p><span>Established 2011 &middot; Company no. 07705672</span><a href="terms.html">Terms &amp; Conditions</a><a class="floating-qr" href="https://oralcom.github.io/alternate-energies/" target="_blank" rel="noopener" aria-label="Open Alternate Energies website QR code"><img src="https://quickchart.io/qr?text=https%3A%2F%2Foralcom.github.io%2Falternate-energies%2F&size=220&margin=2" alt="QR code for Alternate Energies website"></a><a class="floating-back-top" href="#main" aria-label="Scroll to bottom" data-back-top="true">&darr;</a><div class="footer-social-slot"></div></div></footer>';
for(const file of ['index.html','about.html','solutions.html','contact.html',...services.map(s=>s.slug+'.html')]){
 let h=fs.readFileSync(file,'utf8').replace(/<section class="connect-band">[\s\S]*?<\/section>/g,'').replace(/<footer[\s\S]*?<\/footer>/,companyFooter).replaceAll('Our company','About Us');
 fs.writeFileSync(file,h);
}
require('./build-sections.cjs');
